pipeline {
  agent any
  stages {
    stage('Tf platform resources setting'){
      steps {
        withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY', credentialsId: 'AWS-1')]){
          sh '''
          cd Terraform/jenkins-agent/
          pwd
          terraform init
          '''
        }
      }
    }

    stage('Terraform Plan'){
      steps {
        withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY', credentialsId: 'AWS-1')]){
          sh '''
          cd Terraform/jenkins-agent/
          pwd
          terraform plan -input=false -out tfplan
          '''
        }
      }
    }

    stage('Terraform Apply'){
      steps {
        withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY', credentialsId: 'AWS-1')]){
          sh '''
          cd Terraform/jenkins-agent/
          pwd
          terraform apply -input=false tfplan
          '''
          dir('Terraform/jenkins-agent/'){
            script{
              env.INSTANCE_IP = sh(script: 'terraform output -raw instance_public_ip', returnStdout: true).trim()
            }
          sh "echo ${INSTANCE_IP}"
        }
      }
    }
  }
    
    stage('Environment variable value') {
      steps {
        sh 'echo ${INSTANCE_IP}'
            }
          }

  }

} 