---
  - name: Install dependencies
    apt: 
      name: '{{ item }}'
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

  - name: Download MS product repository
    get_url:
      url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
      dest: /tmp/packages-microsoft-prod.deb

  - name: Install MS product repository
    apt: deb=/tmp/packages-microsoft-prod.deb 
    become: true

  - name: Install .NET SDK
    apt:
      name: dotnet-sdk-7.0
      state: present
      update_cache: true