--- 

   
   - name: Removing a user if present
     ansible.builtin.user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512')}}"
      groups: 
        - admin
        - docker
      append: true
      shell: /bin/bash
      system: true
      createhome: yes
      home: /home/{{ username }}
      state: absent
      remove: true
      force: true

   - name: Adding a user to the machine 
     ansible.builtin.user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512')}}"
      groups: 
        - admin
        - docker 
      append: true
      shell: /bin/bash
      system: true
      createhome: yes
      home: /home/{{ username }}
      state: present

    
   - name: Add user to sudoers file
     lineinfile:
        path: /etc/sudoers
        regexp: ^%admin ALL=\(ALL\) ALL$
        insertafter: ^%admin ALL=\(ALL\) ALL$
        line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
        state: present