--- 
   - name: Removing a user if present
     ansible.builtin.user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512')}}"
      group: admin
      append: true
      shell: /bin/bash
      system: true
      createhome: yes
      home: /home/{{ username }}
      state: absent
      remove: true
      force: true

   - name: Adding a user to the machine 
     ansible.builtin.user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512')}}"
      group: admin
      append: true
      shell: /bin/bash
      system: true
      createhome: yes
      home: /home/{{ username }}
      state: present

   - name: Add user to sudoers file
     lineinfile:
        path: /etc/sudoers
        regexp: ^%admin ALL=\(ALL\) ALL$
        insertafter: ^%admin ALL=\(ALL\) ALL$
        line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
        state: present
        
   - name: Create dir for jenkins and give user permission
     ansible.builtin.file:
      path: /opt/jenkins/
      owner: "{{ username }}"
      group: admin
      mode: '0700'
      state: directory