---

- name: CI tools installation/configuration
  hosts: "{{ host_name }}"
  become: true
  vars_files: 
   - vars/all.yaml 
  tasks:
      - name: Install .NET Core
        hosts: your_target_host
        become: true

      

      - name: Install dependencies
        apt:
         name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

      - name: Add Microsoft package repository
        apt_key:
         url: https://packages.microsoft.com/keys/microsoft.asc
         state: present

      - name: Add Microsoft package repository
        apt_repository:
         repo: "deb [arch=amd64] https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod $(lsb_release -cs) main"
         state: present

      - name: Install .NET SDK
        apt:
         name: dotnet-sdk-5.0
         state: present
    # - name: install nginx dependencies 
    #   ansible.builtin.import_role:
    #    name: nginx
 
    # - name: create a user
    #   ansible.builtin.import_role:
    #    name: create-user

    # - name: Install Python
    #   ansible.builtin.import_role:
    #     name: python-3
       
    # - name: install docker 
    #   ansible.builtin.import_role:
    #    name: docker_with_experimental_mode

    # - name: install sonarqube 
    #   ansible.builtin.import_role:
    #    name: sonarqube

    # - name: install sonarscanner 
    #   ansible.builtin.import_role:
    #    name: sonar-scanner       

    # - name: install nvm and node 
    #   ansible.builtin.import_role:
    #     name: nvm_and_node









