---

- name: CI tools installation/configuration
  hosts: "{{ host_name }}"
  become: true
  vars_files: 
   - vars/all.yaml 
  tasks:       
      - name: install docker 
        ansible.builtin.import_role:
          name: docker_with_experimental_mode









