---

- name: CI tools installation/configuration
  hosts: "{{ host_name }}"
  become: true
  vars_files: 
   - vars/all.yaml 
  tasks:
    # - name: install nginx dependencies 
    #   ansible.builtin.import_role:
    #    name: nginx
 
    # - name: create a user
    #   ansible.builtin.import_role:
    #    name: create-user

    # - name: Install Python
    #   ansible.builtin.import_role:
    #     name: python-3
       
    - name: install docker 
      ansible.builtin.import_role:
       name: docker_with_experimental_mode

    # - name: install sonarqube 
    #   ansible.builtin.import_role:
    #    name: sonarqube

    # - name: install sonarscanner 
    #   ansible.builtin.import_role:
    #    name: sonar-scanner       

    # - name: install nvm and node 
    #   ansible.builtin.import_role:
    #     name: nvm_and_node





