pipeline {
    agent {
    label 'Master'
}
    environment {
        ENVIRONMENT = 'DEV'
        APPNAME = 'worker'
    }
    // define environment variable ENVIRONMENT
    parameters {
        string(name: 'TAG', defaultValue: 'latest', description: 'Build version of the Container to be deployed')}
        stages {
            stage('Executing ansible script') {
                steps {
                    withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh '''
                        pwd
                        
                        cd environments/DEV/microservice-deployment/${APPNAME}-application/ansible
                        echo "${WORKSPACE}"
                        echo "${ENVIRONMENT}"
                        echo "${APPNAME}"
                        ansible-playbook main.yaml -i ${WORKSPACE}/Ansible-script/inventory_files/${ENVIRONMENT}-inventory -e "username=${username}" -e "password=${password}" -e "TAG=${TAG}" -e "APPNAME=${APPNAME}" -e "ENVIRONMENT=${ENVIRONMENT}" -vvv
                    '''
                }
            }
        }
    }
}
