---

- name: Deploy Voting Application
  hosts: app_server
  become: true
  tasks:
    - name: Log into DockerHub
      docker_login:
        username: "{{ username }}"
        password: "{{ password }}"
    
    - name: check dir
      shell: pwd
     
    - name: Transfer executable script script
      copy: src=./files/deployment.sh dest=/opt/ mode=0777

    - name: Run Deployment script
      shell: |
        cd /opt/
        pwd
        ls
        echo "yes" | ./deployment.sh
