pipeline {
    agent any
    stages {
        stage('executing terraform script') {
            steps{
                withCredentials([amazonWebServicesCredentials(credentialsId: 'AWS-1', accessKeyVariable:'AWS_ACCESS_KEY_ID', secretKeyVariable:'AWS_SECRET_ACCESS_KEY')])
                sh '''
                terraform init
                terraform plan
                '''

            }
        }
    }
}
