pipeline {
    agent any 
    parameters {
        string(name: 'build_version_vote', defaultValue: 'latest', description: 'Build version of the application to be deployed')}
        stages {
            stage('Executing ansible script') {
                steps {
                    withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh '''
                        pwd
                        cd ./Dev_env_deployments/vote_application/Ansible/
                        ansible-playbook main.yml -i /INFRA-VOTEAPP/Ansible-script/devinventory -e "username=$username" -e "password=$password" -e"build_version=${params.build_version_vote}" -vvv 
                    '''
                }
            }
        }
    }
}
