pipeline {
    agent any
    parameters {
        string(name: 'instance_public_ip', description: 'Public IP address of the EC2 instance')}
    stages {
        stage('creating inventory file') {
            
            steps{
                script{
                    def inventory = "myinventory\n"
                    inventory += "[app_server]\n"
                    inventory += "${params.instance_public_ip} ansible_user=ubuntu\n"

                    writeFile file: 'Application-deployment/inventory', text: inventory
                }
            }
        }
            
        stage('executing ansible script') {
            
            steps{
                 withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh '''
                    cd Application-deployment
                    ansible-playbook main.yml -i inventory -e "username=$username" -e "password=$password" -vvv 
                    '''
            }
        }
    }
}
}