---

- name: Deploy Voting Application
  hosts: app_server
  become: true
  tasks:
    - name: Log into DockerHub
      docker_login:
      username: "{{ username }}"
      password: "{{ password }}"

    - name: Run Deployment script
      command: echo "yes" | deployment.sh