apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres_app.name }}
  labels:
    app: {{ .Values.deploy.postgres_app.image.appName}}
    tags: {{ .Values.tags }}
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres_app.POSTGRES_PASSWORD }}
