---
   - name: install wget
     apt:
      name: wget
      state: present

  #  - name: Install dependencies
  #    apt:
  #     name: net-tools
  #     state: present

  #  - name: jenkins repo
  #    apt_key:
  #     url: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
  #     state: present
  #    become: true


  #  - name: Add Jenkins APT key
  #    apt_key:
  #       url: https://pkg.jenkins.io/debian/jenkins.io.key
  #       state: present


  #  - name: import jenkins key
  #    rpm_key:
  #     state: present
  #     key: https://jenkins-ci.org/redhat/jenkins-ci.org.key



   - name: install jenkins
     apt:
      name: jenkins
      state: present
      update_cache: yes

   - name: Start Jenkins service
     service:
        name: jenkins
        state: started
        enabled: true