---
  - name: install wget
    apt:
      name: wget
      state: present

  - name: Install dependencies
    apt:
      name: net-tools
      state: present

  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /opt/ 


  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: install jenkins
    apt:
      name: jenkins
      state: present
      
  - name: Start Jenkins service
    service:
        name: jenkins
        state: started
        enabled: true