---
   - name: install wget
     apt:
      name: wget
      state: present

   - name: Add Jenkins APT key
     apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

   - name: import jenkins key
     rpm_key:
      state: present
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

   - name: install jenkins
     apt:
      name: jenkins
      state: present

   - name: Start Jenkins service
     service:
        name: jenkins
        state: started
        enabled: true