---
  - name: install wget
    apt:
      name: wget
      state: present

  - name: Install dependencies
    apt:
      name: net-tools
      state: present

  - name: Download Long Term Jenkins release
    get_url:
      url: wget -q - https://pkg.jenkins.io/debian-stable/jenkins.io.key
      dest: /opt/ 

  - name: add GPG key
    apt_key:
      url: gpg --dearmor -o /usr/share/keyrings/jenkins.gpg
      state: present

  - name: sudo
    command: sudo sh -c 'echo deb [signed-by=/usr/share/keyrings/jenkins.gpg] http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    become: true


  - name: install jenkins
    apt:
      name: jenkins
      state: present
      
  - name: Start Jenkins service
    service:
        name: jenkins
        state: started
        enabled: true