pipeline {
  agent { label 'Deploy'}
  parameters {
        string(name: 'vote_app_tag', defaultValue: 'latest')
        string(name: 'result_app_tag', defaultValue: 'latest')
        string(name: 'worker_app_tag', defaultValue: 'latest') }
  environment {
        NAMESPACE = 'qa'
    }
  stages {
    stage('Checking namespace') {
      steps {
        sh '''
          alias k=kubectl 
          value=$(k get namespace | grep ${NAMESPACE}-voting-app)
          if [ -z "$value" ]; then
          k create namespace ${NAMESPACE}-voting-app
          else
          echo "namespace ${NAMESPACE}-voting-app exists"
          fi
        '''
      }
        }
    stage('Helm Deployment') {
      steps {
        sh '''
           helm upgrade --install voting-app ${WORKSPACE}/environments/QA/helm-deployments/voting-application/ --atomic --values ${WORKSPACE}/environments/QA/helm-deployments/voting-application/values.yaml --set deploy.vote_app.image.imageTag=${vote_app_tag} --set deploy.result_app.image.imageTag=${result_app_tag} --set deploy.worker_app.image.imageTag=${worker_app_tag} --namespace ${NAMESPACE}-voting-app
        '''
      }
    }
  }
}