pipeline {
  agent { label 'Deploy'}
  environment {
        NAMESPACE = 'qa'
    }
  stages {
    stage('Checking inventory file') {
      steps {
        sh '''
          alias k=kubectl 
          value=$(k get namespace | grep ${NAMESPACE}-voting-app)
          if [ -z "$value" ]; then
          k create namespace ${NAMESPACE}-voting-app
          else
          echo "namespace ${NAMESPACE}-voting-app exists"
          fi
        '''
      }
        }
    stage('Helm Deployment') {
      steps {
        sh '''
           helm upgrade --install voting-app voting-application/ --atomic --values voting-application/values.yaml --set deploy.vote_app.image.imageTag=83 --set deploy.result_app.image.imageTag=17 --namespace ${NAMESPACE}-voting-app
        '''
      }
    }
  }
}