pipeline {
    agent { label: Master}
    environment {
        ENVIRONMENT = 'DEV'
        APPNAME = 'vote'
    }
    // define environment variable ENVIRONMENT
    parameters {
        string(name: 'TAG', defaultValue: 'latest', description: 'Build version of the Container to be deployed')}
        stages {
            stage('Executing ansible script') {
                steps {
                    withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh '''
                        pwd
                        cd ./environments/DEV/microservice-deployment/${APPNAME}-application/ansible
                        ansible-playbook main.yaml -i ${WORKSPACE}/Ansible-script/${ENVIRONMENT}-inventory -e "username=$username" -e "password=$password" -e "TAG=${params.TAG}" -e "APP-NAME=${APPNAME}"-vvv
                    '''
                }
            }
        }
    }
}
