---

- name: Jenkins-agent configuration
  hosts: "{{ host_name }}"
  become: true
  vars_files: 
   - vars/vars.yaml 
  tasks:
    - name: create a user
      ansible.builtin.import_role:
       name: create-user
       
    - name: install java 
      ansible.builtin.import_role:
       name: jdk-installation

  #   - name: Give password authentication via ssh
  #     become: yes
  #     lineinfile:
  #       path: /etc/ssh/sshd_config
  #       # The String to Search
  #       regexp: '^PasswordAuthentication no$'
  #       # The String to Replace
  #       line: "PasswordAuthentication yes"
  #       state: present
  #       backup: yes
  #     notify: restart ssh

  # handlers:
  #   - name: restart ssh
  #     service:
  #       name: sshd 
  #       state: restarted

        