apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.redis_app.name }}
  labels:
    app: {{ .Values.deploy.redis_app.image.appName }}
    tags: {{ .Values.tags }}
spec:
  ports:
  - port: {{ .Values.service.redis_app.port }}
    targetPort: {{ .Values.service.redis_app.targetPort }}

  selector:
    app: {{ .Values.deploy.redis_app.image.appName}}
